version: '2'
services:
    commerzbank-app:
        image: commerzbank
        external_links:
            - commerzbank-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/commerzbank?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    commerzbank-mysql:
        extends:
            file: mysql.yml
            service: commerzbank-mysql
